# GitHub Actions Documentation: https://docs.github.com/en/actions
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          coverage: none

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Generate application key
        run: php artisan key:generate

      - name: Statically analize code (Larastan & PHPStan)
        run: ./vendor/bin/phpstan analyse

  tests:
    name: Tests (PHP ${{ matrix.php-version }}) on ${{ matrix.os }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ 8.0, 8.1 ]
        dependencies: [ lowest, highest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Generate application key
        run: php artisan key:generate

      - name: Run tests (PHPUnit)
        run: php artisan test
